name: Test Greeting

on:
  push:
    branches:
      - main
      - renReal

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check actor
      run: echo "Hello There @${{ github.actor }}!"
