name: Hello World

on:
  push:
    branches:
      - main  # Replace with your branch names

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello World"
