name: hello auto

on:
  push:
    branches:
      - main
      - epril  

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say hello auto
        run: echo "working!"
